services:
  api:
    image: rest-chess
    build: .
    environment:
      - API_HOST=api
      - PYTHONDONTWRITEBYTECODE=1
      - FLASK_APP=restchess/entrypoints/flask_app.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/code
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - --port=80
    ports:
      - "5000:80"
